const cardsData = [
  {
    id: 1,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 2,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 3,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 4,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 5,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 6,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 7,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 8,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 9,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
  {
    id: 10,
    name: 'Аффинированный мерный слиток из золота',
    price: '10534$',
    carat: 18,
    sampe: 750,
    mass: 30,
    width: 37,
    height: 22,
  },
];

export default cardsData;
