import React from 'react';
import './globals.css';
import Header from '@/components/header/Header';
import { sfProDisplay } from '@/utils/fonts';
import Footer from '@/components/footer/Footer';

export const metadata = {
  title: 'DFA',
  description: 'Generated by the smilest developers',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sfProDisplay.className}>
        <div className="wrapper">
          <Header />
          <main className="main">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
